services:
  web:
    build: .
    command: ./bin/dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - rails_storage:/rails/storage
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
      - TZ=Asia/Tokyo
      - BINDING=0.0.0.0

volumes:
  rails_storage:
